%Reglas
hombre(german).
hombre(efren).
hombre(daniel).
hombre(reynaldo).
hombre(arcadio).
hombre(emilio).
hombre(david).
hombre(ismael).
hombre(mario).
mujer(gabriela).
mujer(alejandra).
mujer(gloria).
mujer(isabel).
mujer(silvia).
mujer(carolina).
mujer(elvira).
mujer(adriana).
mujer(andrea).
mujer(mariana).
mujer(mayte).

progenitor(german,efren).
progenitor(german,daniel).
progenitor(german,alejandra).
progenitor(gabriela,efren).
progenitor(gabriela,daniel).
progenitor(gabriela,alejandra).
progenitor(reynaldo,german).
progenitor(reynaldo,silvia).
progenitor(reynaldo,carolina).
progenitor(reynaldo,elvira).
progenitor(isabel,german).
progenitor(isabel,silvia).
progenitor(isabel,carolina).
progenitor(isabel,elvira).
progenitor(arcadio,gabriela).
progenitor(arcadio,adriana).
progenitor(arcadio,emilio).
progenitor(arcadio,david).
progenitor(gloria,gabriela).
progenitor(gloria,adriana).
progenitor(gloria,emilio).
progenitor(gloria,david).
progenitor(adriana,ismael).
progenitor(adriana,andrea).
progenitor(adriana,mariana).
progenitor(adriana,mayte).
progenitor(mario,ismael).
progenitor(mario,andrea).
progenitor(mario,mariana).
progenitor(mario,mayte).

pareja(german,gabriela).
pareja(gabriela,german).
pareja(reynaldo,isabel).
pareja(isabel,reynaldo).
pareja(gloria,arcadio).
pareja(arcadio,gloria).
pareja(adriana,mario).
pareja(mario,adriana).

padre(X,Y):-hombre(X),progenitor(X,Y).
madre(X,Y):-mujer(X),progenitor(X,Y).
hermanos(X,Y):-progenitor(Z,X),progenitor(Z,Y).
hermano(X,Y):-hombre(X),hermanos(X,Y).
hermana(X,Y):-mujer(X),hermanos(X,Y).
esposo(X,Y):-hombre(X),pareja(X,Y).
esposa(X,Y):-mujer(X),pareja(X,Y).
suegro(X,Y):-padre(X,Z),pareja(Y,Z).
suegra(X,Y):-madre(X,Z),pareja(Y,Z).
yerno(X,Y):-suegro(Y,X);suegra(Y,X),hombre(X).
nuera(X,Y):-suegro(Y,X);suegra(Y,X),mujer(X).
cunados(X,Y):-(pareja(X,Z),hermanos(Z,Y));(pareja(Y,Z),hermanos(Z,X)).
cunado(X,Y):-cunados(X,Y),hombre(X).
cunada(X,Y):-cunados(X,Y),mujer(X).
abuelo(X,Y):-progenitor(Z,Y),padre(X,Z).
abuela(X,Y):-progenitor(Z,Y),madre(X,Z).
nieto(X,Y):-(abuelo(Y,X);abuela(Y,X)),hombre(X).
nieta(X,Y):-(abuelo(Y,X);abuela(Y,X)),mujer(X).
tio(X,Y):-progenitor(Z,Y),hermano(X,Z).
tiomaterno(X,Y) :- progenitor(Z,Y),hermano(X,Z), mujer(Z).
%tio(X,Y):-prigenitor(Z,Y),(hermano(X,Z);cunado(X,Z)).
tia(X,Y):-progenitor(Z,Y),hermana(X,Z).
tiapaterna(X,Y) :- progenitor(Z,Y),hermana(X,Z), hombre(Z).
primo(X,Y):-progenitor(Z,X),progenitor(W,Y),hermanos(W,Z),hombre(X).
%primo(X,Y) :- (tio(Z,Y) ; tia(Z,Y)) , progenitor(Z,X), hombre(X).
prima(X,Y):-progenitor(Z,X),progenitor(W,Y),hermanos(W,Z),mujer(X).
